### PR TITLE
Upgrade plugin for Sylius 1.9

### PR DESCRIPTION
**Pull request by swan-andre**
Made some updates to the plugin files to adapt it for Sylius 1.9.

### CODE REVIEW

**Comment by Geolim4** [comment]
Poke @DjLeChuck :)

**Comment by DjLeChuck** [comment]
Yes, sorry I'm on holidays! 😁
I'm back mid-september to check this! 👍🏻

**Comment by DjLeChuck** [comment]
Thank you for your code!

I'm using it as a base for a new version, stay tuned!

**Comment by DjLeChuck** [comment]
[Here we GO! 🚀](https://github.com/umanit/sylius-product-variant-attribute-plugin/releases/tag/1.9.0)

**Pull request closed without merging**
